//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Completed.
        /// </summary>
        internal static string Form1_backgroundWorker_RunWorkerCompleted_Game_Complete {
            get {
                return ResourceManager.GetString("Form1_backgroundWorker_RunWorkerCompleted_Game_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game already running.
        /// </summary>
        internal static string Form1_btnStart_Click_Game_already_running {
            get {
                return ResourceManager.GetString("Form1_btnStart_Click_Game_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters must be numeric.
        /// </summary>
        internal static string Form1_btnStart_Click_Parameters_must_be_numeric {
            get {
                return ResourceManager.GetString("Form1_btnStart_Click_Parameters_must_be_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Car Finders and setting up initial data ....
        /// </summary>
        internal static string Form1_btnStart_Click_Starting_Game {
            get {
                return ResourceManager.GetString("Form1_btnStart_Click_Starting_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Cancelled.
        /// </summary>
        internal static string Form1_CancelProcess_Game_Cancelled {
            get {
                return ResourceManager.GetString("Form1_CancelProcess_Game_Cancelled", resourceCulture);
            }
        }
    }
}
